heat_template_version: 2016-04-08

description: This template creates additional scripts required to provision a Big-IP.

parameters:
  # Optional Usage Analytics
  ua_allow:
    type: boolean
    label: Allow Usage Analytics
    description: Toggles whether non-identifiable statistical information is sent to F5.
    default: true
  ua_template_name:
    type: string
    label: Template Name (Usage Analytics)
    description: Name of the template used to launch the stack
    default: None
  ua_template_version:
    type: string
    label: Template Version (Usage Analytics)
    description: Version of the template used to launch the stack
    default: None
  ua_cloudlibs_tag:
    type: string
    label: f5-cloud-libs Tag (Usage Analytics)
    description: Tag that identifies cloudlibs version
    default: None
  ua_project_id:
    type: string
    label: Project ID (Usage Analytics)
    description: ID of the template user
    default: None
  ua_region:
    type: string
    label: Region (Usage Analytics)
    description: Region where template is launched
    default: None
  ua_stack_id:
    type: string
    label: Stack Id (Usage Analytics)
    description: Stack Id or Name
    default: None
  ua_license_type:
    type: string
    label: License Type (Usage Analytics)
    description: Type of Licensing
    default: BYOL

  verify_hash_url_override:
    type: string
    label: Script verifyHash override source URL
    description: The URL to the source of verifyHash script override
    default: None
  bigip_addon_licenses:
    type: comma_delimited_list
    label: Additional VE License Keys
    description: f5 TMOS License Add-On Keys.
    default:
      -
  bigip_license:
    type: string
    label: Primary VE License Base Key
    description: f5 TMOS License Basekey
    default: None
  modules:
    type: json
    label: Modules to provision on the BIG-IP.
    description: A list of modules to provision and their respective levels. <module_name:level>
  ntp:
    type: comma_delimited_list
    label: NTP servers
    description: A list of NTP servers
    default:
      -
  dns:
    type: comma_delimited_list
    label: Domain Name Servers
    description: A list of Domain Name Servers
    default:
      -
  remote_hosts_names:
    type: comma_delimited_list
    label: f5 BIG-IP VE Remote Host Names
    description: A list of remote hosts to add to the BIG-IP
    default:
      -
  remote_hosts_ips:
    type: comma_delimited_list
    label: f5 BIG-IP VE Remote Host IP Addresses
    description: A list of remote host ips to add to the BIG-IP. The index should match the entries provided in bigip_remote_hosts_names
    default:
      -
  timezone:
    type: string
    label: Time Zone
    description: Time Zone to configure the device with
    default: UTC
  host_name:
    type: string
    label: Host Name
    description: BIG-IP Host Name
  management_port_id:
    type: string
    label: Management Port ID
    description: Neutron Port ID of the BIG-IP Management NIC
  management_port:
    type: number
    label: Management Port
    description: Management port for the BIG-IP admin
  ssh_key_name:
    type: string
    label: SSH Key Name
    description: SSH Key Name to inject for Big-IP Access.
  use_config_drive:
    type: boolean
    label: Enable Config Drive
    description: Determines if cloud init data is polled from config drive instead of metadata service.
    default: false
  wait_handle_curl:
    type: string
    label: Wait Handle
    description: Resolved curl_cli value of the WaitConditionHandle that enables status signals to be sent back to Heat
  wait_handle_curl_options:
    type: string
    label: Wait Handle Curl Additional Options
    description: Additonal options to add to curl_cli value of the WaitConditionHandle that enables status signals to be sent back to Heat
    default: None
  db_vars:
    type: comma_delimited_list
    label: DB Variables
    description: Custom DB Variable values in the format <key:value>
    default:
      -
resources:
  onboarding_scripts:
    type: OS::Heat::CloudConfig
    properties:
      cloud_config:
        merge_how: dict(recurse_array,no_replace)+list(append)
        write_files:
          - path: /config/verifyHash
            permissions: 0755
            owner: root:root
            content: { get_file: ../scripts/verifyHash }
          - path: /config/preOnboard.sh
            permissions: 0755
            owner: root:root
            content:
              str_replace:
                params:
                  __remote_hosts_names__: { get_param: remote_hosts_names }
                  __remote_hosts_ips__: { get_param: remote_hosts_ips }
                  __ssh_key_name__: { get_param: ssh_key_name }
                  __use_config_drive__: { get_param: use_config_drive }
                  __verify_hash_override__: { get_param: verify_hash_url_override }
                  __wc_notify_options__: { get_param: wait_handle_curl_options }
                  wc_notify: { get_param: wait_handle_curl}
                template: { get_file: ../scripts/preOnboard.sh }
          - path: /config/wait-cloudlibsInstall.sh
            permissions: 0755
            owner: root:root
            content: { get_file: ../scripts/wait-cloudlibsInstall.sh }
          - path: /config/encrypt.sh
            permissions: 0755
            owner: root:root
            content: { get_file: ../scripts/encrypt.sh }
          - path: /config/postOnboard.sh
            permissions: 0755
            owner: root:root
            content:
              str_replace:
                params:
                  __wc_notify_options__: { get_param: wait_handle_curl_options }
                  wc_notify: { get_param: wait_handle_curl}
                template: { get_file: ../scripts/postOnboard.sh }
          - path: /config/onboard.sh
            permissions: 0755
            owner: root:root
            content:
              str_replace:
                params:
                  __license__: { get_param: bigip_license }
                  __host_name__: { get_param: host_name }
                  __mgmt_port_id__: { get_param: management_port_id }
                  __mgmt_port__: { get_param: management_port }
                  __add_on_licenses__:
                    list_join:
                      - ' '
                      -
                        repeat:
                          template: --add-on "addon"
                          for_each:
                            addon: {get_param: bigip_addon_licenses}
                  __dns__:
                    list_join:
                      - ' '
                      -
                        repeat:
                          template: --dns server_dns
                          for_each:
                            server_dns: {get_param: dns}
                  __modules__:
                    list_join:
                      - ' '
                      -
                        repeat:
                          template: --module bigip_module
                          for_each:
                            bigip_module: {get_param: modules}
                  __ntp__:
                    list_join:
                      - ' '
                      -
                        repeat:
                          template: --ntp server_ntp
                          for_each:
                            server_ntp: { get_param: ntp }
                  __timezone__: { get_param: timezone }
                  __allow_ua__: { get_param: ua_allow }
                  __template_name__: { get_param: ua_template_name }
                  __template_version__: { get_param: ua_template_version }
                  __cloudlibs_tag__: { get_param: ua_cloudlibs_tag }
                  __cust_id__: { get_param: ua_project_id }
                  __deploy_id__: { get_param: ua_stack_id }
                  __region__: { get_param: ua_region }
                  __license_type__: { get_param: ua_license_type }
                  __db_vars__:
                    list_join:
                      - ' '
                      -
                        repeat:
                          template: --db db_var
                          for_each:
                            db_var: {get_param: db_vars}
                  __wc_notify_options__: { get_param: wait_handle_curl_options }
                  wc_notify: { get_param: wait_handle_curl }
                template: { get_file: ../scripts/onboard.sh }

outputs:
  OS::stack_id:
    description: The F5::BigIP::OnboardingScripts resource.
    value:
      get_resource: onboarding_scripts
