heat_template_version: 2016-04-08

description: This template configures network components for a standard f5 standalone VE image.

parameters:
  script_path:
    type: string
    label: Script Path
    description: Full path of the onboard network script
    default: /config/onboard-network.sh
  default_gateway:
    type: string
    label: Default Gateway IP
    description: Upstream Gateway IP Address for VE instances.
    default: None
  vlan_names:
    type: comma_delimited_list
    label: f5 BIG-IP VE VLAN name
    description: Name of the VLAN to be created/referenced on the BIG-IP.
  vlan_mtus:
    type: comma_delimited_list
    label: f5 BIG-IP VE VLAN MTU
    description: MTU value of the VLAN on the BIG-IP.
  vlan_tags:
    type: comma_delimited_list
    label: f5 BIG-IP VE VLAN tags
    description: Tag to apply on the VLAN on the BIG-IP. VLAN default is untagged.
    default: None
  nic_count:
    type: number
    label: f5 BIG-IP NIC count
    description: The number of additional NICs for the BIG-IP excluding management NIC.
    default: 1
  self_ip_names:
    type: comma_delimited_list
    label: f5 BIG-IP VE VLAN SelfIP Names
    description: Self-IP names to assign
    default:
      -
  self_ip_addrs:
    type: comma_delimited_list
    label: f5 BIG-IP VE VLAN SelfIP Address
    description: Self-IP address to associate with the BIG-IP VLAN.
  self_cidr_blocks:
    type: comma_delimited_list
    label: f5 BIG-IP VE VLAN CIDR Block
    description: CIDR Block for the BIG-IP SelfIP address.
  self_port_lockdowns:
    type: comma_delimited_list
    label: f5 BIG-IP VE VLAN Allow Services
    description: Optional list of <service:port> lockdown settings for the VLAN. If no value is supplied, default port lockdown settings are used.
    default:
      -
  wait_handle_curl:
    type: string
    label: Wait Handle
    description: Resolved curl_cli value of the WaitConditionHandle that enables status signals to be sent back to Heat.
  wait_handle_curl_options:
    type: string
    label: Wait Handle Curl Additional Options
    description: Additonal options to add to curl_cli value of the WaitConditionHandle that enables status signals to be sent back to Heat
    default: None

resources:
  onboard_network_config:
    type: OS::Heat::CloudConfig
    properties:
      cloud_config:
        merge_how: dict(recurse_array,no_replace)+list(append)
        write_files:
          - path: { get_param: script_path }
            permissions: 0755
            owner: root:root
            content:
              str_replace:
                params:
                  __default_gateway__: { get_param: default_gateway }
                  __network_vlan_name__: { get_param: vlan_names }
                  __network_vlan_create__:
                    repeat:
                      template: "True"
                      for_each:
                        vlan: { get_param: vlan_names }
                  __network_vlan_tag__: { get_param: vlan_tags}
                  __network_vlan_mtu__: { get_param: vlan_mtus}
                  __network_vlan_nic__: ""
                  __network_self_name__: { get_param: self_ip_names}
                  __network_self_ip_addr__: { get_param: self_ip_addrs}
                  __network_self_cidr_block__: { get_param: self_cidr_blocks }
                  __network_self_port_lockdown__: { get_param: self_port_lockdowns }
                  __network_vlan_nic_count__: { get_param: nic_count}
                  __wc_notify_options__: { get_param: wait_handle_curl_options }
                  wc_notify: { get_param: wait_handle_curl }
                template: { get_file: ../scripts/onboard-network-nnic.sh}
outputs:
  OS::stack_id:
    description: F5::BigIP::OnboardNetworkConfigNNic resource.
    value: { get_resource: onboard_network_config }
  config_id:
    value: {get_resource: onboard_network_config }
